version: '3.8'

services:
  db:
    container_name: mysql-autosync
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: autosync
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Servidor de Email DEV
  mail-dev:
    container_name: mail-dev-autosync
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  # Bucket
  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: bucket-dev-autosync
    ports:
      - "9000:9000" #API
      - "9001:9001" #Console Web
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  mysql:
    driver: local